@tool
class_name AWOCError extends Node

const ARRAY_NOT_INITILIZED: int = 1
const ELEMENT_EXISTS: int = 1
const ELEMENT_DOES_NOT_EXIST: int = 1
const ARRAY_NOT_CREATED: int = 1
const ELEMENT_NOT_ADDED: int = 1
const INVALID_NAME: int = 1
const INVALID_PATH: int = 1
const PATH_NOT_OPENED: int = 1
const DIRECTORY_NOT_CREATED: int = 1
const SAVE_RES_FAILED: int = 1
const UID_NOT_FOUND: int = 1
const UID_NOT_FOUND_IN_RES: int = 1
const PATH_NOT_RETURNED_FROM_UID: int = 1
const RESOURCE_NOT_LOADED: int = 1
const RESOURCE_ON_DISK_NOT_DELETED: int = 1
const RESOURCE_ID_NOT_DELETED: int = 1
const RESOURCE_NOT_INITILIZED: int = 1
const RESOURCE_ID_NOT_FOUND_IN_DICTIONARY: int = 1
const RESOUCE_PATH_NOT_FOUND_IN_DICTIONARY: int = 1
const RESOURCE_NOT_FOUND_IN_DICTIONARY: int = 1

const NO_MESHES_FOUND_IN_SOURCE_SKELETON: int = 1
const SOURCE_SKELETON_NOT_FOUND: int = 1
const NO_BONES_IN_SOURCE_SKELETON: int = 1
const NO_BONES_IN_SKELETON_RESOURCE: int = 1
const NO_MESH_SURFACE_ARRAY: int = 1

const NO_MESH_SURFACE_FOUND: int = 1
const NO_MESH_RESOURCE_SURFACE_FOUND: int = 1

const MUST_BE_IN_EDITOR: int = 1

const SUCCESS = 100
