@tool
class_name AWOCError extends Node

const SLOTS_NOT_INITILIZED: int = 1
const SLOT_EXISTS: int = 2
const SLOT_DOESNT_EXIST: int = 3
const HIDE_SLOT_EXISTS: int = 4
const HIDE_SLOT_DOESNT_EXIST: int = 5
const ARRAY_NOT_CREATED = 6
const SLOT_NOT_ADDED = 7
const INVALID_NAME = 8
const INVALID_PATH = 9

const AVATAR_PATH_NOT_OPENED: int = 1
const AVATAR_DIR_NOT_CREATED: int = 1

const SKELETON_RES_SAVE_FAILED: int = 1
const SKELETON_UID_NOT_FOUND: int = 1
const NO_MESH_CHILDREN_FOUND_IN_SOURCE_SKELETON: int = 1
const NO_MESHES_FOUND_IN_SOURCE_SKELETON: int = 1
const SKELETON_ID_NOT_FOUND: int = 1
const SKELETON_RES_NOT_LOADED: int = 1
const SOURCE_SKELETON_NOT_FOUND: int = 1
const NO_BONES_IN_SOURCE_SKELETON: int = 1
const NO_BONES_IN_SKELETON_RESOURCE: int = 1
const SKELETON_NOT_INITILIZED: int = 1

const INVALID_MESH_TO_DELETE: int = 1
const MESH_ID_NOT_FOUND: int = 1
const PATH_NOT_RETURNED_FROM_MESH_UID: int = 1
const MESH_DIR_NOT_OPENED: int = 1
const MESH_RESOUCE_NOT_DELETED: int = 1
const MESH_ID_NOT_DELETED: int = 1
const INVALID_MESH_PATH: int = 1
const SAVE_MESH_RESOURCE_ERROR: int = 1
const MESH_NOT_LOADED: int = 1
const NO_MESH_SURFACE_FOUND: int = 1
const NO_MESH_SURFACE_ARRAY: int = 1
const MESH_NOT_INITILIZED: int = 1
const NO_MESH_RESOURCE_SURFACE_FOUND: int = 1
const MESH_NOT_FOUND_IN_MESH_DICTIONARY: int = 1
const MESH_NOT_FOUND_IN_MESH_IDS_DICTIONARY: int = 1
const MESH_RESOURCE_NOT_LOADED: int = 1
const MESH_EXISTS: int = 1

const MUST_BE_IN_EDITOR: int = 1

const SUCCESS = 100
